from typing import List, Dict, Any, Optional, Protocol

class VectorStore(Protocol):
    def upsert(self, embeddings: List[List[float]], metadatas: List[Dict[str, Any]]) -> None: ...
    def search(self, query_emb: List[float], k: int = 8, where: Optional[Dict[str, Any]] = None) -> List[Dict[str, Any]]: ...
    def stats(self) -> Dict[str, Any]: ...
