from typing import List, TypedDict, Dict

class ResearchState(TypedDict):
    """
    Represents the state of our research agent. This class acts as a "memory"
    to hold information as the agent moves through the research workflow.

    Attributes:
        topic: The initial research topic provided by the user.
        queries: A list of search queries generated by the planner agent.
        urls: A list of URLs found from the web search.
        documents: A list of processed documents, each containing its content and source URL.
        report: The final, synthesized research report.
    """
    topic: str
    queries: List[str]
    urls: List[str]
    documents: List[Dict[str, str]]
    report: str

